train_data: "../data/Titanic-Dataset.csv"
test_data: "../data/tested.csv"
directory_scores: "../scores"

decision_tree_parameters:
    max_depth: [3]
    min_samples_split: [2]
    min_samples_leaf: [1]

random_forest_parameters:
    n_estimators: [100]
    max_depth: [3]
